name: wechat_camera_picker_demo
description: A new Flutter project.
version: 3.6.4+20
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  wechat_camera_picker: ^3.7.0
  sliding_up_panel: ^2.0.0+1


  package_info_plus: ^1.4.2
  video_player: ^2.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/
